### ISSUE TITLE
Shows update that doesn't exist

### ISSUE THREAD

**Issue by Tigereye13** [mangerlahn/Latest#279]
It keeps showing that Alba (from Apple Arcade) has an update to version 4.1.15 on Nov 7. Every time I try to update the app it doesn't work. After looking around online that update doesn't exist. The latest update was last year to version 3.0.2156.

**Comment by mangerlahn** [comment]
Thank you for reporting! This is unfortunately an issue with Apple. The iPad version of the game is currently on 4.1.15. The Apple endpoint Latest asks for update information returns iPad version information for certain apps. To my knowledge, there is nothing I can do about it. Sorry!

As a workaround, you can select the app and hit Ignore from the context menu, so that the update does not show up anymore.

**Comment by mangerlahn** [comment]
I just released v0.10, could you check whether that resolves this? I had several reports of this over the years and never managed to reproduce it.

**Comment by Tigereye13** [comment]
Thanks. I updated Latest but it didn’t fix it. Actually now it’s both saying to update Alba and it’s saying to update Vero desktop beta to public release when it’s only in beta

**Comment by mangerlahn** [comment]
I can't provide a fix for Alba, this is on Apple. What does it show for Vero?

**Comment by mangerlahn** [comment]
Ok, I've added Vero to the list in #297, thanks for the report!
