### ISSUE TITLE
Two Apps Showing Updates When on Latest Version

### ISSUE THREAD

**Issue by JLP04** [mangerlahn/Latest#342]
MacOS Sonoma 14.2.1 (ARM)
Latest 0.10.3

Two apps, BambuStudio and Cinebench (MacOS App Store Version) are showing as having updates when I have the latest version: 
<img width="291" alt="Screenshot 2024-01-14 at 4 06 03 PM" src="https://github.com/mangerlahn/Latest/assets/63068340/fd67c997-a7a4-432a-a444-fb783b22f7b2">
<img width="306" alt="Screenshot 2024-01-14 at 4 06 06 PM" src="https://github.com/mangerlahn/Latest/assets/63068340/d3330815-9c97-4008-b621-036d76f670b1">

Cinebench has always shown as having updates, so that specific app having issues was not introduced recently, but I figured I'd mention it as well while apps are being fixed in Latest.

**Comment by alex-ioma** [comment]
Hi I do have a similar issue with apps that are based on Electron and that were previously installed via homebrew. 
In my case: 
- Lens have a version mismatch - Lens says it is already at the latest version but Latest says it needs updating
- Obsidian has been updated by the installer and (form the app) is correctly showing the same new version reported in Latest, but Latest shows the installed version fixed at the version of the installer.

<img width="288" alt="Screenshot 2024-01-16 at 11 36 55 PM" src="https://github.com/mangerlahn/Latest/assets/76006253/a50fe593-dc55-4a36-9722-ed0bd11c23ef">

**Comment by mangerlahn** [comment]
Should be fixed now :)

**Comment by JLP04** [comment]
Cinebench is still showing up.

**Comment by alex-ioma** [comment]
Actually, Obsidian is still showing and Lens completely disappeared from the list as if it wasn't installed.
